language: java
jdk:
    -openjdk8
branches:
    only:
        - master
cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.gradle'
script: "./gradlew clean build"

before_deploy:
    - zip -r the-actual-webservice *
    - mkdir -p deploy
    - mv the-actual-webservice.zip deploy/the-actual-webservice.zip
deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
      secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
      bucket: actual-springboot-build
      region: ap-northeast-2
      skip_cleanup: true
      acl : private
      local_dir: deploy
      wait-until-deployed: true


    - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
      secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
      bucket: actual-springboot-build
      key: the-actual-webservice.zip

      bundle_type: zip
      application: the-actual-webservice
      deployment_group: the-actual-webservice-group
      region: ap-northeast-2
      wait-until-deployed: true

notifications:
    email:
        recipients:
            - ijin17463@gmail.com
            